### ISSUE TITLE
Is there a possible way to add new buttons and change some interface

### ISSUE THREAD

**Issue by thusila** [makehumancommunity/communityassets#6]

**Comment by joepal1976** [comment]
This issue is completely malplaced:

* This repository is for storing assets, it has nothing to do with the makehuman gui
* Bug reports are not a proper place for requesting general support.

Please see http://www.makehumancommunity.org/wiki/FAQ:What_is_the_prefered_method_for_contacting_the_MakeHuman_crew%3F
